# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('praises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='praise',
            name='number_of_hearts',
            field=models.IntegerField(default=0),
        ),
    ]
